server:
    port: 4880

logging:
    level:
        com : DEBUG

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    data:
        mongodb:
            authentication-database : db_nx
            username : John_Woo
            password : 2hJ$lDS#nA&8
            database : db_nx
            port : 27017
            host : localhost
      
resourceServer:
    client-jwkKeyUri: http://localhost:4800/oauth/token_key
    client-id: resourceserver
    client-secret: resourceserversecret