logging:
    level:
        com : DEBUG
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB  
spring:
    data:
        mongodb:
            authentication-database : db_nx
            username : John_Woo
            password : 2hJ$lDS#nA&8
            database : db_nx
            port : 27017
            host : mongodb:27017      
resourceServer:
    client-jwkKeyUri: http://resourceserver:4800/oauth/token_key
    client-id: resourceserver
    client-secret: resourceserversecret
server:
    port: 4880     

