server:
    port: 4880

logging:
    level:
        com : debug
        org.springframework.cloud.commons.util.InetUtils: trace

spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
            
    data:
        mongodb:
            authentication-database : db_nx
            username : John_Woo
            password : "{cipher}9ab20fcbd9aa12128beb9a67eadea40420b9e3bb576e50e49378277195c7d82f"
            database : db_nx
            port : 27017
            host : localhost 
    zipkin:
        baseUrl: http://localhost:9411
    sleuth:
        sampler:
            rate: 100
    cloud:
        stream:
            bindings:
                input:
                    destination: userDetailsPrepare
                    content-type: application/json
                    group: userDetailsPrepareGrup  
            kafka:
                binder:
                    zkNodes: localhost
                    brokers: localhost
        inetutils:
            ignored-interfaces:
                - Hyper.*
                - docker0
                - host.*               
            preferred-networks:
                - localhost
            timeout-seconds: 10                 

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        securePortEnabled: true
    instance:
        hostname: localhost    
        securePortEnabled: true
        securePort: ${server.port}
           
security:
    oauth2:
        client:
            client-id: resourceserver
            client-secret: resourceserversecret
        resource:
            jwt:
                key-uri: https://localhost:4800/oauth/token_key

redisserver:
    server: localhost
    port: 6379                