server:
    port: 4800
    
logging:
    level: 
        com: DEBUG

keystore:
  password: password
  privateKey: cronos.jks
  alias: cronos_server

authentication_database:
  url: postgres:5432
  db: db_users
  username: postgres
  password: "{cipher}aae90af54edb4b8755c97279e9b578b32b28335f5f09ebbffd3b647731e85f4d"
  
spring: 
  mail:
    host: smtp.gmail.com
    port: 587
    username: eugenfazekas.mailtrap@gmail.com
    password: "{cipher}2aa6738619358207b4079a8dfc907eb762725da0f037fd616bf66f92391ec960"
    properties:
      mail:
        smtp:
          starttls:
            enable: true
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1          

emailservice:
  subjecten: Demo Project account activation
  text1en: Dear
  text2en: "Thanks for you're registration to our website, and you can sign is with the followed username: "
  text3en: You can activate you're account by the followed link    
  validationLink: http://127.0.0.1:4800/api1/v1/user/userKeyCheck/     
  
client:
  secret: secret 
  
resource:
  service:
    base:
      url: http://resourceservice:4880 
    
resourceService:
  client-id: resourceserver
  client-secret: resourceserversecret

