server:
    port: 5555
    ssl:
        key-alias: gateway_server
        key-store: src/main/resources/keystore/gateway_server.jks
        key-store-password: gatewayserverpassword
        trust-store: src/main/resources/keystore/cacerts
        trust-store-password: changeit
        client-auth: need

eureka:    
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        hostname: gateway-server
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/gatewaytoapi1/**
          filters:
          - RewritePath=/gatewaytoapi1/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: resource-service
          uri: lb://resource-service
          predicates:
          - Path=/gatewaytoapi2/**
          filters:
          - RewritePath=/gatewaytoapi2/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        httpclient:
            ssl:
                handshake-timeout-millis: 10000
                close-notify-flush-timeout-millis: 3000
                close-notify-read-timeout-millis: 0