server:
    port: 5555
    ssl:
        key-alias: gateway_server
        key-store: src/main/resources/keystore/gateway_server.jks
        key-store-password: gatewayserverpassword
        key-store-type: PKCS12
        trust-store: src/main/resources/keystore/truststore.jks
        trust-store-password: authoritypassword

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        securePortEnabled: true
    instance:
        hostname: localhost     
        instance-id: ${spring.application.name}:${server.port}
        securePortEnabled: true
        securePort: ${server.port}
        nonSecurePortEnabled: false
        
logging:
    level:
        org.springframework.cloud.commons.util.InetUtils: trace

spring:
    zipkin:
        baseUrl: http://localhost:9411
    sleuth:
        sampler:
            percentage: 1
    cloud:
        loadbalancer.ribbon.enabled: false
        gateway:
            routes:
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
              - Path=/gatewaytoapi1/**
              filters:
              - RewritePath=/gatewaytoapi1/(?<path>.*), /$\{path}
              - RemoveRequestHeader= Cookie,Set-Cookie
            - id: resource-service
              uri: lb://resource-service
              predicates:
              - Path=/gatewaytoapi2/**
              filters:
              - RewritePath=/gatewaytoapi2/(?<path>.*), /$\{path}
              - RemoveRequestHeader= Cookie,Set-Cookie       
            httpclient:
                ssl:
                    handshake-timeout-millis: 10000
                    close-notify-flush-timeout-millis: 3000
                    close-notify-read-timeout-millis: 0
                  
              