server:
    port: 5555
    ssl:
        enabled: true
        key-store-type: PKCS12
        key-store: classpath:keystore/domain.p12
        key-alias: skipper
        key-store-password: skipperpassword
        trust-store: C:\Program Files\Java\jdk-11.0.11\lib\security\cacerts
        trust-store-password: changeit

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/gatewaytoapi1/**
          filters:
          - RewritePath=/gatewaytoapi1/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: resource-service
          uri: lb://resource-service
          predicates:
          - Path=/gatewaytoapi2/**
          filters:
          - RewritePath=/gatewaytoapi2/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        httpclient:
            ssl:
              useInsecureTrustManager: true