server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
      
spring:
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/auth/**
          filters:
          - RewritePath=/auth/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: resource-service
          uri: lb://resource-service
          predicates:
          - Path=/resource/**
          filters:
          - RewritePath=/resource/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie