server:
    port: 5555
    ssl:
      key-alias: skipper
      key-store-type: PKCS12
      key-store: classpath:keystore/domain.p12
      key-store-password: skipperpassword
      trust-store: classpath:keystore/truststore
      trust-store-password:  skipperpassword

eureka:    
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        hostname: gateway-server
        instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
          - Path=/gatewaytoapi1/**
          filters:
          - RewritePath=/gatewaytoapi1/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        - id: resource-service
          uri: lb://resource-service
          predicates:
          - Path=/gatewaytoapi2/**
          filters:
          - RewritePath=/gatewaytoapi2/(?<path>.*), /$\{path}
          - RemoveRequestHeader= Cookie,Set-Cookie
        httpclient:
            ssl:
              useInsecureTrustManager: true