server:
    port: 5555

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        securePortEnabled: true
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        securePortEnabled: true
        securePort: ${server.port}
        nonSecurePortEnabled: false
        
logging:
    level:
        org.springframework.cloud.commons.util.InetUtils: trace

spring:
    zipkin:
        baseUrl: http://localhost:9411
    sleuth:
        sampler:
            percentage: 1
    cloud:
        loadbalancer.ribbon.enabled: false
        gateway:
            routes:
            - id: authentication-service
              uri: lb://authentication-service
              predicates:
              - Path=/gatewaytoapi1/**
              filters:
              - RewritePath=/gatewaytoapi1/(?<path>.*), /$\{path}
              - RemoveRequestHeader= Cookie,Set-Cookie
            - id: resource-service
              uri: lb://resource-service
              predicates:
              - Path=/gatewaytoapi2/**
              filters:
              - RewritePath=/gatewaytoapi2/(?<path>.*), /$\{path}
              - RemoveRequestHeader= Cookie,Set-Cookie
        inetutils:
            ignored-interfaces:
                - Hyper.*
                - docker0
                - host.*                
            preferred-networks:
                - localhost
            timeout-seconds: 10        
    httpclient:
        ssl:
          useInsecureTrustManager: true
                  
              